services:
  problem_02_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: problem_02_web
    image: problem_02_web:0.1
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    networks:
      - problem_02_network
    volumes:
      - ./:/rails

networks:
  problem_02_network:
    external: true