version: '3'

services:
  problem_02_db:
    image: postgres:latest
    container_name: problem_02_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - problem_02_network
    restart: always

  problem_02_pgadmin:
    image: dpage/pgadmin4
    container_name: problem_02_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - problem_02_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - problem_02_network
    restart: always

  problem_02_web:
    image: twotanawin/problem_02_web:0.1
    container_name: problem_02_web
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - problem_02_db
    networks:
      - problem_02_network
    restart: always

volumes:
  pgadmin_data:

networks:
  problem_02_network:
    external: true
